### ISSUE TITLE
visualization of stats

### ISSUE THREAD

**Issue by paradite** [yangshun/nuswhispers-leaderboard#2]
hi!
i've made a quick visualization app for the leaderboard, at https://github.com/paradite/viz-nus.
demo: http://paradite.github.io/viz-nus/
if you like it, maybe we can integrate it somehow?

**Comment by yangshun** [comment]
Hi, this is pretty nice. I wouldn't say it's a necessity, but no harm in showing this. Could you edit index.html and allow users to toggle between these two different modes?

**Comment by paradite** [comment]
okay i'm on it. there might be slight style inconsistencies since i am not using angular.

**Comment by paradite** [comment]
submitted pull request, there are some style variations like font size, presence of photo, but the main content should be okay.

**Comment by yangshun** [comment]
Oops you did make an issue to ask about it. I totally forgot about this. My bad >_<. Closed by #3
